title: My Awesome Site               # The title of your site
description: This is my blog.        # A short description
baseurl: ""                          # The base URL for your site (if applicable)
url: "https://username.github.io"   # Your site's URL
theme: jekyll-theme-slate            # The theme you're using
markdown: kramdown                   # Markdown processor
plugins:                              # List of plugins (if allowed)
  - jekyll-feed                       # Example of a plugin
  - jekyll-seo-tag                   # SEO plugin

# Custom variables
author: "Your Name"
social_links:                         # Custom data
  twitter: "https://twitter.com/username"
  github: "https://github.com/username"
